from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "母版-20260506-Clone-分支净化回测.py"
OUT_DIR = Path(__file__).resolve().parent / "branch_strategies"

DEFAULT_MODES = [
    "normal",
    "force_v227",
    "force_rzq",
    "force_zb",
    "force_rzq_zb",
    "force_auction",
]


def make_copy(mode: str) -> Path:
    src_text = SRC.read_text(encoding="utf-8")
    marker = "g.branch_test = 'normal'"
    replacement = f"g.branch_test = '{mode}'"
    if marker not in src_text:
        raise SystemExit(f"Cannot find expected marker: {marker}")

    patched = src_text.replace(marker, replacement, 1)
    header = (
        "# Auto-generated by codex_strategy_dissection/make_branch_strategy_copies.py\n"
        f"# Source: {SRC.name}\n"
        f"# Branch test mode: {mode}\n"
        "# Keep this file inside codex_strategy_dissection for isolated replay only.\n\n"
    )
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f"mother_branch_{mode}.py"
    out_path.write_text(header + patched, encoding="utf-8")
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--modes", nargs="+", default=DEFAULT_MODES)
    args = parser.parse_args()

    for mode in args.modes:
        out_path = make_copy(mode)
        print(f"{mode}: {out_path}")


if __name__ == "__main__":
    main()
